#!/usr/bin/env python3
"""Generate ``web/wordlist.js`` from the bundled EFF Large Wordlist.

The web generator embeds the wordlist as a JavaScript constant so the
page works from ``file://`` and fully offline, with no ``fetch()`` —
which is what lets the site ship a Content-Security-Policy containing
no ``connect-src`` at all.

This script is the only way ``web/wordlist.js`` should ever change: it
re-reads the canonical list bundled with the Python package, verifies
the pinned SHA-256 (the same digest asserted in
``tests/test_passphrase.py``), and rewrites the JS file.

Usage:
    python tools/build_web_wordlist.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

# SHA-256 of https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
# with CRLF normalized to LF. Must match tests/test_passphrase.py.
PINNED_SHA256 = "addd35536511597a02fa0a9ff1e5284677b8883b83e986e43f15a3db996b903e"
WORDLIST_SIZE = 7776

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "password_key" / "data" / "eff_large_wordlist.txt"
TARGET = ROOT / "web" / "wordlist.js"

HEADER = """\
// Generated by tools/build_web_wordlist.py — do not edit by hand.
//
// EFF Large Wordlist for random passphrases (7,776 words, ~12.9 bits
// of entropy per word), by the Electronic Frontier Foundation, used
// under CC BY 3.0: https://www.eff.org/dice
//
// Source of truth: src/password_key/data/eff_large_wordlist.txt
// (SHA-256 pinned there by tests/test_passphrase.py and re-verified
// by the build script before this file is written).
"use strict";
"""


def main() -> int:
    data = SOURCE.read_bytes()
    digest = hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()
    if digest != PINNED_SHA256:
        print(
            f"refusing to build: {SOURCE}\n"
            f"  SHA-256 {digest}\n"
            f"  expected {PINNED_SHA256}",
            file=sys.stderr,
        )
        return 1
    # Each line is "<dice roll>\t<word>"; only the word matters here
    # (same parse as password_key.passphrase.load_wordlist).
    words = [
        line.split("\t")[-1].strip()
        for line in data.decode("utf-8").splitlines()
        if line.strip()
    ]
    if len(words) != WORDLIST_SIZE:
        print(
            f"refusing to build: expected {WORDLIST_SIZE} words, got {len(words)}",
            file=sys.stderr,
        )
        return 1
    body = json.dumps(words, separators=(",", ":"))
    TARGET.parent.mkdir(exist_ok=True)
    # newline="" keeps the LF endings on Windows; Path.write_text only grew
    # a newline argument in 3.10 and this package supports 3.9.
    with TARGET.open("w", encoding="utf-8", newline="") as handle:
        handle.write(f"{HEADER}const EFF_WORDLIST = Object.freeze({body});\n")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(words)} words)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
